### ISSUE TITLE
Page indicator is not showing

### ISSUE THREAD

**Issue by boogdan** [evgenyneu/Auk#10]
Hey, 

First of all thank you for this image slideshow, your work is amazing.
I have some difficulties implementing your code and I don't understand where's the problem. 
Everything is working great except the page indicator which is not showing.

Here's an extremely short version of your demo code that I've tried:

...
let remoteImageBaseUrl = "http://evgenii.com/files/2015/06/auk_demo/"
    let remoteImages = [
        (
            fileName: "Alca_Impennis_by_John_Gould.jpg",
            description: "Alca impennis by John Gould: The Birds of Europe, vol. 5 pl. 55, 19th century."
        ),
        (
            fileName: "Great_Auk_Egg_Bent.jpg",
            description: "Great Auk egg, U. S. National Museum, in a book by Arthur Cleveland Bent, 1919."
        ),
        (
            fileName: "Great_auk_with_juvenile.jpg",
            description: "Great auk with juvenile drawing by John Gerrard Keulemans, circa 1900."
        ),
        (
            fileName: "Keulemans-GreatAuk.jpg",
            description: "Great Auks in summer and winter plumage by John Gerrard Keulemans, before 1912."
        ),
        (
            fileName: "SimlulateNoImage.jpg",
            description: "No image test."
        )
    ]

override func viewDidLoad() {
        super.viewDidLoad()

        Moa.settings.cache.requestCachePolicy = .UseProtocolCachePolicy
        scrollView.delegate = self
        scrollView.auk.settings.placeholderImage = UIImage(named: "logo.png")
        scrollView.auk.settings.errorImage = UIImage(named: "error_image.png")
        //showInitialImage()
        scrollImages()
    }

    func scrollImages(){
        
        for image in remoteImages {
            let url = "\(remoteImageBaseUrl)\(image.fileName)"
            scrollView.auk.show(url: url)
        }
        
    }

....

Where should I look?

**Comment by evgenyneu** [comment]
Hi @boogdan, thanks for the kind words. This is strange, I have put your code into a new project and it does show page indicator for me. I don't know why it does not work for you. If you could isolate your case into a demo app and attach it here I will have a look. Thanks.

Here is this demo:
[UsingAuk_2016_03.zip](https://github.com/evgenyneu/Auk/files/181076/UsingAuk_2016_03.zip)

**Comment by boogdan** [comment]
Hi Evgenii, thanks for your fast reply. 

Your demo is working flawlessly on my end, however I did a test project using the same code except that I've used Cocoapods for including Auk and the page indicatior is missing again. Maybe this is a clue?

Here's my demo:
[scrolltest.zip](https://github.com/evgenyneu/Auk/files/181234/scrolltest.zip)

**Comment by evgenyneu** [comment]
Oh, this was a tricky one. It appears the scroll view (and constraints) was installed into a non-Any size class.

Here is why page indicator was missing. The app was adding images to the scroll view in viewDidLoad. But because the scroll view was installed in a non-default size class it was not yet added to the view hierarchy and its `superview` property was nil. Auk creates page indicator the first time an image is added to it. In this case the page indicator was not created because the scrollView's superview was nil (page indicator is added to scroll view's superview).


<img width="256" alt="size_class" src="https://cloud.githubusercontent.com/assets/880411/13904002/6dc8e76c-eee5-11e5-93b8-ef02dbd8a2f7.png">

I have installed the scroll view and constraints to default Any size class and it seems to be working.
[scrolltest_2.zip](https://github.com/evgenyneu/Auk/files/181243/scrolltest_2.zip)

**Comment by boogdan** [comment]
Hi Evgenii,

Sorry for the late reply. Nice catch, that was indeed the problem. 
In my project I must use a non any-size class so moving the function call from viewDidLoad() to viewDidAppear() did the trick and the page indicator appeared.

**Comment by evgenyneu** [comment]
Thanks for reporting this oddity. It may help other people.
