### ISSUE TITLE
How to update pageIndex?

### ISSUE THREAD

**Issue by Darwinium** [evgenyneu/Auk#19]
Hi,
I don't understood how to update the index of Image. I've tried this way ( imageIndex is a label on my UIView) but it's doesn't work(

`override func viewDidLoad() {
        super.viewDidLoad()
        
        if let scrollView = scrollView {
            scrollView.auk.show(image: UIImage(named: "image1")!)
            scrollView.auk.show(image: UIImage(named: "image2")!)
            
            imageIndex.text = String(scrollView.auk.currentPageIndex)
        }   
    }
`
Always showed "Option(0)". I guess it's a pageIndex of first image but how I can update it? Where and when?

Thanks a lot and sorry, I'm a new coder. Your library is cool!

**Comment by evgenyneu** [comment]
Hi @Darwinium, good quesion. In order to update a label with the current page number one needs to detect the moment when user scrolls the scroll view. It can be done by implementing a scroll view delegate with the `scrollViewDidScroll` method:

1) Firstly, subclass your view controller from `UIScrollViewDelegate`:

```Swift
class ViewController: UIViewController, UIScrollViewDelegate {
```

2) Secondly, assign the view controller to the delegate property of the scroll view. Make sure to assign the delegate **before** accessing scrollView.auk property.

```Swift
override func viewDidLoad() {
    super.viewDidLoad()

    scrollView.delegate = self
    scrollView.auk.show(...
```

3) Finally, implement `scrollViewDidScroll` method in your view controller. In this method you can update your label with the index of the current page. 

```Swift
func scrollViewDidScroll(scrollView: UIScrollView) {
   imageIndex.text = String(scrollView.auk.currentPageIndex)
}
```

Good luck and let me know how it goes.

**Comment by Darwinium** [comment]
Hi again, **evgenyneu**

Thanks, it's work!

Few more questions:
1. How can I bind the picture to the bottom of UIScrollView regardless of the size of the image?
Example how's now:
http://joxi.ru/krDkgY1T0z09KA
http://joxi.ru/eAO6EP0h4j4ej2
2. How can I do something like this? http://joxi.ru/Q2KqgPDH9J9Q8r

Thank you again and have a nice day)

**Comment by evgenyneu** [comment]
No worries. Sorry I do not understand your question. Can you explain a bit more? Do you want to show a part of the next image in the scroll view?

**Comment by Darwinium** [comment]
Exactly!

**Comment by evgenyneu** [comment]
Hi @Darwinium, unfortunately Auk only shows a single image at a time. But you can create such image view that shows a portion of the next image yourself. Here is a demo: https://github.com/evgenyneu/SneakPeekScroll

**Comment by evgenyneu** [comment]
Closing this issue. Feel free to reopen when needed.
