### ISSUE TITLE
Scroll view will scroll or finished scrolling?

### ISSUE THREAD

**Issue by Jmaguerre** [evgenyneu/Auk#21]
Hi!
Is there a way from the view controller to know if the scroll view started a scroll or finished? I need to update other views in the view controller accordingly. For example, each image has an author that took the picture and I want to show that name using the current index.

I saw that you use a delegate to load remote images when the superview becomes visible. It will be something similar but for local images.

Thanks!

**Comment by evgenyneu** [comment]
Hello @Jmaguerre, in order to show the author name for the the current page number one needs to detect the moment when user scrolls the scroll view. It can be done by implementing a standard scroll view delegate with the `scrollViewDidScroll` method:

1) Firstly, subclass your view controller from `UIScrollViewDelegate`:

```Swift
class ViewController: UIViewController, UIScrollViewDelegate {
```

2) Secondly, assign the view controller to the delegate property of the scroll view. Make sure to assign the delegate **before** accessing scrollView.auk property.

```Swift
override func viewDidLoad() {
    super.viewDidLoad()

    scrollView.delegate = self
    scrollView.auk.show(...
```

3) Finally, implement `scrollViewDidScroll` method in your view controller. In this method you can update your label with the index of the current page. 

```Swift
func scrollViewDidScroll(scrollView: UIScrollView) {
   imageIndex.text = String(scrollView.auk.currentPageIndex)
}
```

Note that `scrollViewDidScroll` method is called very frequently as the scroll view is being scrolled.  Does it answer your question?

**Comment by Jmaguerre** [comment]
Awesome, I understood perfectly. Thanks for the help.

**Comment by evgenyneu** [comment]
Excellent, you can also look at the demo app which does similar thing to what you want to do. It shows the author name for the currently shown painting.

**Comment by evgenyneu** [comment]
Closing this issue. Feel free to reopen if needed.
