### ISSUE TITLE
Auk inside a UITableViewCell

### ISSUE THREAD

**Issue by schwarzh80** [evgenyneu/Auk#24]
Hi Evgenii,

I just integrated Auk into my project (storyboard with auto layout). I have a ViewController hosting a TableViewController with a prototype cell. In this cell, there is a ScrollView that I am extending with Auk programatically and show two remote images with it.

When the view loads initially, everything works completely perfect. Both images are loading and the pageControl is moving as expected. But as soon as I scroll down the TableView and back up again, it destroys the ScrollView/Auk. I assume, that something goes wrong, when the cell is reused.

Do you have any experiences with Auk in TableViewCells?
Did I do anything wrong?

Thanks a lot and keep up the good work!
Frank

**Comment by evgenyneu** [comment]
Hi @schwarzh80, this is a very interesting use case. No, I have not placed an Auk scroll view in a table view cell before.

Do you call the show(url: ) method when you dequeue a tableview cell?

**Comment by schwarzh80** [comment]
Hi Evgenii,

Yes it's inside the `cellForRowAtIndexPath`:

```
let cell = tableView.dequeueReusableCellWithIdentifier("TableViewCellScrollView", forIndexPath: indexPath) as! TableViewCellScrollView
                
scrollView = cell.scrollView
scrollView.delegate = self
                
scrollView.backgroundColor = UIColor(red: 25/255, green: 30/255, blue: 35/255, alpha: 1)
scrollView.auk.settings.pageControl.backgroundColor = UIColor.clearColor()
scrollView.auk.settings.placeholderImage = UIImage(named: "detail_placeholder")
                
scrollView.auk.removeAll()
                
scrollView.auk.show(url: "https://pixabay.com/static/uploads/photo/2012/02/17/15/24/new-york-14480_960_720.jpg")
scrollView.auk.show(url: "https://pixabay.com/static/uploads/photo/2015/03/11/12/31/new-york-668616_960_720.jpg")
                
return cell
```

And I should have mentioned, what happens, when I scroll up again. It seems to reinitialize the ScrollView and the first image is shown. But the second image only shows it's placeholder and the pageControl isn't working anymore.

I have attached you a small demo project, where you can see what happens.
[Auk Test.zip](https://github.com/evgenyneu/Auk/files/265958/Auk.Test.zip)

Thanks!
Frank

**Comment by evgenyneu** [comment]
Hi, thanks for the code, I found the issue. The scroll view stops working on the second dequeuing because the delegate is assigned in the ViewController file.

```Swit
   scrollView.delegate = self
```

It is ok to assign the delegate but it must be done **before** the `auk` property is accessed. Auk assigns its own delegate to the scroll view. That's how it tracks the scrolling events (scrollViewDidScroll) and loads the images when needed. But if we assign the delegate after the `auk` is accessed we remove Auk's delegate and it is no longer able to do the job. That's why the second time it did not load the second image or update the page control. 

If you need to use the delegate you can assign it the first time only by checking if it's nil. Let me know how it goes.

**Comment by schwarzh80** [comment]
Hi Evgenii, 

Now everything is working perfectly, the delegate was the small piece I have overseen.

Thanks again for your support and keep up the amazing job!

Cheers,
Frank

**Comment by evgenyneu** [comment]
No worries, good luck with your project.

**Comment by satyamub** [comment]
Hi @evgenyneu  @schwarzh80  I tried that before with this kind of code, it was working correctly however when I try to autoscroll it crashed

[SliderWithTableView.AutoCancellingTimerInstance (AutoCancellingTimerInstance.timerFired(_:))]: unrecognized selector sent to instance 0x7fa90be65f90
2016-05-18 19:06:58.526 SliderWithTableView[6407:272883] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SliderWithTableView.AutoCancellingTimerInstance (AutoCancellingTimerInstance.timerFired(_:))]: unrecognized selector sent to instance 0x7fa90be65f90'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000108d55e65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010acc1deb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000108d5e48d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x0000000108cab90a ___forwarding___ + 970
	4   CoreFoundation                      0x0000000108cab4b8 _CF_forwarding_prep_0 + 120
	5   Foundation                          0x00000001093650d1 __NSFireTimer + 83
	6   CoreFoundation                      0x0000000108cb5c84 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	7   CoreFoundation                      0x0000000108cb5831 __CFRunLoopDoTimer + 1089
	8   CoreFoundation                      0x0000000108c77241 __CFRunLoopRun + 1937
	9   CoreFoundation                      0x0000000108c76828 CFRunLoopRunSpecific + 488
	10  GraphicsServices                    0x000000010dea4ad2 GSEventRunModal + 161
	11  UIKit                               0x000000010979d610 UIApplicationMain + 171
	12  SliderWithTableView                 0x00000001086c535d main + 109
	13  libdyld.dylib                       0x000000010b7d192d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

Any Idea?

**Comment by satyamub** [comment]
Got it. I have changed the #selector syntax to old syntax as I have not updated the code to Swift 2.2 yet thats why its failing. Can you guys tell me what to use there below for swift 2.1

timer = NSTimer.scheduledTimerWithTimeInterval(interval, target: self,
      selector: #selector(AutoCancellingTimerInstance.timerFired(_:)), userInfo: nil, repeats: repeats)

**Comment by evgenyneu** [comment]
Hi, @satyamub, you can use the `2.0` version if you are using CocoaPods or Carthage in order for it to work in Swift 2.1. More information [here](https://github.com/evgenyneu/Auk/wiki/Previous-versions).

**Comment by satyamub** [comment]
@evgenyneu Hi I am using this manually, can you give me the source code for Swift 2.1

**Comment by satyamub** [comment]
@evgenyneu  Got it man thanks.. Working on that

**Comment by evgenyneu** [comment]
Very good, @satyamub, let me know if you have any issues.

**Comment by evgenyneu** [comment]
Closing this issue, looks like it is resolved. Feel free to reopen when needed.
