### ISSUE TITLE
How to enable page indicator?

### ISSUE THREAD

**Issue by danielpassos** [evgenyneu/Auk#28]
What I need to do to enable the page indicator? I cloud not find any reference about it in your demo app.

```swift
    override func viewDidLoad() {
        scrollView.auk.settings.showsHorizontalScrollIndicator = true
        scrollView.auk.settings.pageControl.visible = true
        scrollView.auk.settings.contentMode = UIViewContentMode.ScaleAspectFill
        
        let image1 = UIImage(named: "banner_top.jpg")
        self.scrollView.auk.show(image: image1!, accessibilityLabel: "Top")
        
        let image2 = UIImage(named: "banner_conteudo.jpg")
        self.scrollView.auk.show(image: image2!, accessibilityLabel: "Conteúdo")
        
        let image3 = UIImage(named: "banner_eventos.jpg")
        self.scrollView.auk.show(image: image3!, accessibilityLabel: "Eventos")
        
        scrollView.auk.startAutoScroll(delaySeconds: 3)
    }
``` 

![2016-05-29 18-28-38](https://cloud.githubusercontent.com/assets/13337/15636107/396642d6-25cb-11e6-8816-1a977d0df0a6.png)

**Comment by evgenyneu** [comment]
Hi @danielpassos, this is weird indeed. The page indicator should be visible by default. This issue could appear if the scroll view is not added to the main view in `viewDidLoad` where you add the images. Here is why:

* The page indicator view is created the first time you add an image to the scroll view.
* The page indicator view is added to the superview of the scroll view.
* If the scroll view has no superview at the time the images are added, the page indicator will not be created.

One person had a similar issue because the scroll view was not install in the default size class, therefore it was not in the main view during the `viewDidLoad` call.

<img width="221" alt="size_classes" src="https://cloud.githubusercontent.com/assets/880411/15636433/bce7f520-2641-11e6-8ef3-1b4613cb1513.png">

I hope that helps. Let me know how it goes.

**Comment by danielpassos** [comment]
@evgenyneu 

Thanks for the very awesome reply. Thanks for the very awesome reply. The only thing come in my mind now, is this view controller is embedded in a `Container View`.

Anyway, I will try to reproduce the same scenario and play around tomorrow morning. I can publish it in my Github account and let you know here. 

Thanks for the reply again!

**Comment by evgenyneu** [comment]
The container view may be the cause. To do a quick check I would print the value of `scrollView.superview` in the function where you show the images. If it's `nil` then the page control will not be created. In this case, you may want to show the images after the scroll view is added to the view, in viewWillAppear, for example.

**Comment by danielpassos** [comment]
Yeap, it is the problem, but seems I have the same using `viewWillAppear`

```swift```
override func viewDidLoad() {
    print("scrollView.superview = \(scrollView.superview)")
}

```

```
scrollView.superview = nil
```

```swift
override func viewWillAppear(animated: Bool) {
    print("scrollView.superview = \(scrollView.superview)")
}
```

```
scrollView.superview = nil
```

**Comment by danielpassos** [comment]
I did the same scenario I have in the [clean/new app](https://github.com/danielpassos/Auk-Playground) and it works like a charm with the same code, so it's seem be a specific problem in my project. I'll investigate. Thanks for your help anyway

![auk-playground](https://cloud.githubusercontent.com/assets/13337/15653873/1a964f5e-2666-11e6-82da-5f560dee0886.png)
