### ISSUE TITLE
Objective-c support

### ISSUE THREAD

**Issue by taher-mosbah** [evgenyneu/Auk#43]
Hello,

I'm trying to integrate Auk into an Obective-c project using cocoapods.
I modified Auk class declaration to add @objc
```
@objc public class Auk : NSObject {

  public override init() {

  }
```
I added use_frameworks! to my podfile and set Defines Module to YES in my build settings.
In my class I import it like this
``` #import <Auk/Auk-Swift.h> //(I tried @import Auk; too)```
and then : 
```[self.gallerySV.auk showWithUrl:imageUrl accessibilityLabel:nil];```
The code is working but I only can access methodes in Auk.swfit (AukSettings for example is not recognised by Xcode ..)

Do you have any idea how to properly do this and do you intend to support integrating with objective-c (maybe in a branch ?)

Thanks !

**Comment by evgenyneu** [comment]
Hello @taher-mosbah, thanks for bringing this up. You did everything correctly. The reason the AukSettings is not visible in ObjC is because, to my knowledge, ObjC does not recognize swift structures, only classes ([stackoverflow link](http://stackoverflow.com/questions/26173234/how-to-use-swift-struct-in-objective-c)).

One way to use Auk in an ObjC app is to create a wrapper class in Swift. Here is such [sample class](https://github.com/evgenyneu/Auk/blob/master/Demo/AukObjCBridge.swift) with few methods and [instrutions](https://github.com/evgenyneu/Auk/wiki/Using-Auk-in-Objective-C-project) on how to use it in ObjC app.

I am not planning to add ObjC support at this moment because it would add complexity and require additional maintenance.

Let me know how it goes.

**Comment by taher-mosbah** [comment]
Hello @evgenyneu thanks for your answer and for adding the sample 👍 
It's working great but I ended using another lib (https://github.com/zvonicek/ImageSlideshow) as I wanted to use the image manager I already have on my project (using ImageSlideshow this is done by subclassing InputSource), maybe this can be a nice addition to Auk ?
Thanks again !
Cheers

**Comment by evgenyneu** [comment]
Thanks for the tip about the InputSource, I will investigate that.

All the best
